### ISSUE TITLE
Main page event order

### ISSUE THREAD

**Issue by kele6ra** [js-machine/js-machine-app#55]
Event order on main page is from right to left (Arabic style).

**Comment by DrJekill352** [comment]
https://trello.com/c/Q91htvrU/53-bug-%D0%B1%D0%B0%D0%B3-%D1%81-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%BE%D0%B9-%D0%BD%D0%B0%D0%B7%D0%B0%D0%B4-%D0%BF%D1%80%D0%B8-%D0%B7%D0%B0%D1%85%D0%BE%D0%B4%D0%B5-%D0%B8%D0%B7-vk-%D0%B2%D0%BD%D0%B5%D1%88%D0%BD%D0%B8%D0%B9-%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81

**Comment by DrJekill352** [comment]
After discussion with development team. We closed that issues as that is not a defect.
