### ISSUE TITLE
Route issue

### ISSUE THREAD

**Issue by kele6ra** [js-machine/js-machine-app#57]
If you open news page from another site you can't route to main page, button "назад" not working, and there is not any home button.

**Comment by DrJekill352** [comment]
issue will be fixed soon
https://trello.com/c/Q91htvrU/53-bug-%D0%B1%D0%B0%D0%B3-%D1%81-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%BE%D0%B9-%D0%BD%D0%B0%D0%B7%D0%B0%D0%B4-%D0%BF%D1%80%D0%B8-%D0%B7%D0%B0%D1%85%D0%BE%D0%B4%D0%B5-%D0%B8%D0%B7-vk-%D0%B2%D0%BD%D0%B5%D1%88%D0%BD%D0%B8%D0%B9-%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81

**Comment by DrJekill352** [comment]
Fixed
